### ISSUE TITLE
Retrive Attributes on another intent

### ISSUE THREAD

**Issue by mrroccodev** [cameronhunter/alexa#10]
I am not being able to retrieve the attributes on another intent with the session open. I am sending the attributes like this:
return Response.say(msg)
                                 .attributes({ index:  PaginationSize})
                                 .shouldEndSession(false)
                                 .build();

But I am not being able to capture that on another intent.

**Comment by cameronhunter** [comment]
`say` always ends the session because the user can't interact with the skill afterwards. Use `ask` instead.
