### ISSUE TITLE
Add prettier to remove need for code-style nits

### ISSUE THREAD

**Issue by cameronhunter** [cameronhunter/alexa#8]
There's no need to hassle contributors with simple code-style complaints that can be fixed automatically. Let's add `prettier` to the codebase and add it as a commit hook.

**Comment by billyvg** [comment]
I usually use `husky` + `lint-staged` for pre commit hooks. I can add these + `prettier` when i get some free time if you want.

**Comment by cameronhunter** [comment]
Sounds good to me 👌

**Comment by cameronhunter** [comment]
Resolved by PR #11
